# Generated by Django 4.0.4 on 2022-06-24 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=10)),
                ('sort_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(verbose_name='data of birth')),
                ('work_exp', models.IntegerField()),
                ('sort_num', models.IntegerField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.direction')),
            ],
        ),
    ]
